# Setup
title:        Filter Mason
tagline:      Build Filters for Snapchat
baseurl:      ""
paginate:     1
permalink:    :title

# About/contact
author:
  name:       Spacesift LLC
  url:        http://spacesift.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown