# Setup
title:        Filter Mason
tagline:      Build Filters for Snapchat
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Spacesift LLC
  url:        http://filtermason.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown